version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    restart: always
    links:
      - db:db_domain
    depends_on:
      - db
      - keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - start-dev
    ports:
      - "8081:8081"
    environment:
      KC_HTTP_PORT: 8081
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin


  db:
    container_name: yandex-lavka-db
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql/dbvolume
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure



volumes:
  dbvolume:

networks:
  default:
