version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    restart: always
    links:
      - db:db_domain
    depends_on:
      - db

  db:
    container_name: yandex-lavka-db
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql/dbvolume
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      DB_ADDR: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      - db

volumes:
  dbvolume:

networks:
  default:
